// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/login.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/rhyme.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/LoginForm.tsx";
import * as $$2 from "./islands/Rhyme.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/login.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/rhyme.tsx": $3,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/LoginForm.tsx": $$1,
    "./islands/Rhyme.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
